-- 1. KATEGORI
CREATE TABLE public.kategori (
    id_kategori BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_kategori TEXT NOT NULL
);

-- 2. BARANG
CREATE TABLE public.barang (
    kode_barang TEXT PRIMARY KEY,
    nama_barang TEXT NOT NULL,
    id_kategori BIGINT DEFAULT 0,
    harga_jual BIGINT NOT NULL DEFAULT 0,
    stok BIGINT NOT NULL DEFAULT 0,
    barcode TEXT,
    merek TEXT,
    tipe_motor TEXT,
    harga_beli BIGINT DEFAULT 0,
    harga_beli_dus BIGINT DEFAULT 0,
    satuan TEXT,
    lokasi_rak TEXT
);

-- 3. USERS (Custom table for app users, distinct from Supabase Auth users)
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    pin TEXT NOT NULL,
    role TEXT NOT NULL,
    avatar TEXT,
    email TEXT,
    phone TEXT,
    address TEXT
);

-- 4. TRANSAKSI
CREATE TABLE public.transaksi (
    id_transaksi TEXT PRIMARY KEY,
    tanggal_transaksi TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    total_harga BIGINT NOT NULL,
    payment_method TEXT DEFAULT 'Tunai',
    service_fee NUMERIC DEFAULT 0,
    status_lunas TEXT DEFAULT 'Lunas',
    mechanic_id BIGINT,
    mechanic_name TEXT,
    notes TEXT
);

-- 5. DETAIL TRANSAKSI
CREATE TABLE public.detail_transaksi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_transaksi TEXT NOT NULL REFERENCES public.transaksi(id_transaksi),
    kode_barang TEXT NOT NULL,
    nama_barang TEXT NOT NULL,
    jumlah BIGINT NOT NULL,
    harga_satuan BIGINT NOT NULL,
    subtotal BIGINT NOT NULL
);

-- 6. AUTH SESSIONS (For QR Code Login)
CREATE TABLE public.auth_sessions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    status TEXT DEFAULT 'pending', -- pending, authenticated, expired
    user_id BIGINT REFERENCES public.users(id),
    device_info TEXT
);

-- ENABLE ROW LEVEL SECURITY (Optional for now, but good practice. We allow anon access for simplicity first)
ALTER TABLE public.kategori ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.barang ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaksi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detail_transaksi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.auth_sessions ENABLE ROW LEVEL SECURITY;

-- OPEN ACCESS POLICY (Use with caution - for development simplicity)
CREATE POLICY "Enable all access for all users" ON public.kategori FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for all users" ON public.barang FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for all users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for all users" ON public.transaksi FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for all users" ON public.detail_transaksi FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for all users" ON public.auth_sessions FOR ALL USING (true) WITH CHECK (true);

-- SEED INITIAL USERS
INSERT INTO public.users (name, pin, role, avatar) VALUES 
('Owner', '123456', 'Owner', 'https://ui-avatars.com/api/?name=Owner&background=0D8ABC&color=fff'),
('Kasir', '000000', 'Kasir', 'https://ui-avatars.com/api/?name=Kasir&background=6b7280&color=fff');

-- SEED INITIAL CATEGORIES
INSERT INTO public.kategori (nama_kategori) VALUES 
('Oli'), ('Sparepart'), ('Service'), ('Ban'), ('Aksesoris');

-- 7. MECHANICS (New table for mechanics data only, distinct from Users/Accounts)
CREATE TABLE public.mechanics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    avatar TEXT,
    email TEXT,
    phone TEXT,
    address TEXT,
    status TEXT DEFAULT 'Aktif',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.mechanics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for all users" ON public.mechanics FOR ALL USING (true) WITH CHECK (true);

-- 8. STORE SETTINGS (Single row table for store configuration)
CREATE TABLE public.store_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name TEXT DEFAULT 'Star Jaya Mobile',
    store_address TEXT DEFAULT 'Jl. Raya Contoh No. 123',
    store_phone TEXT DEFAULT '081234567890',
    receipt_footer TEXT DEFAULT 'Terima Kasih sudah berbelanja!',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for all users" ON public.store_settings FOR ALL USING (true) WITH CHECK (true);

-- SEED INITIAL SETTINGS
INSERT INTO public.store_settings (store_name, store_address, store_phone, receipt_footer)
SELECT 'Star Jaya Mobile', 'Jl. Raya Contoh No. 123', '081234567890', 'Terima Kasih sudah berbelanja!'
WHERE NOT EXISTS (SELECT 1 FROM public.store_settings);
