-- Migration to separate Mechanics from Users
CREATE TABLE IF NOT EXISTS public.mechanics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    avatar TEXT,
    email TEXT,
    phone TEXT,
    address TEXT,
    status TEXT DEFAULT 'Aktif',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.mechanics ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all access for all users" ON public.mechanics;
CREATE POLICY "Enable all access for all users" ON public.mechanics FOR ALL USING (true) WITH CHECK (true);
